### ISSUE TITLE
Spring cleaning checklist for repo

### ISSUE THREAD

**Issue by machow** [rstudio/pins-python#185]
- [ ] : change author in setup.cfg to me and Posit, PBC (cf [pins-r DESCRIPTION](https://github.com/rstudio/pins-r/blob/main/DESCRIPTION#L11))
- [ ] : just use my posit email for both for now
- [ ] : add Julia's pypi.org account as maintainer
- [ ] : do some light reading on what maintainer means in pyproject.toml
- [ ] : change license holder to "Pins Python Authors"
- [ ] : update code of conduct
