### ISSUE TITLE
Tracking Issue - Pyright Compliance

### ISSUE THREAD

**Issue by nathanjmcdougall** [rstudio/pins-python#272]
This is a tracking issue for addressing stricter compliance with `pyright`:

```[tasklist]
### Tasks
- [ ] `reportArgumentType`: None defaults without None in their type hint, Variety of other issues
- [ ] `reportAssignmentType`: Only one change needed - to avoid trying to treat Traversable as Path
- [ ] `reportAttributeAccessIssue`: Variety of issues
- [ ] `reportCallIssue`: Passing extra args to the IFileSystem Protocol, Missing overloads for as_df arg in pin_search and pin_versions
- [ ] `reportGeneralTypeIssues`: Return type issues in CachePruner.versions and pins.constructors.board
- [ ] `reportIncompatibleMethodOverride`: Issues with ExtendMethodDoc, RSConnect implementation of the IFileSystem Protocol
- [ ] `reportIncompatibleVariableOverride`: Only one change needed in RsConnectFs; protocol: ClassVar[str | tuple[str, ...]]
- [ ] `reportIndexIssue`: Using __delitem__ on a Mapping, RSConnect API Reponse object issues
- [ ] `reportMissingImports`: https://github.com/rstudio/pins-python/issues/262#issuecomment-2240875273
- [ ] `reportMissingTypeStubs`: Missing stubs for fsspec: https://github.com/fsspec/filesystem_spec/issues/625, Missing stubs for joblib: https://github.com/joblib/joblib/issues/1516
- [ ] `reportOptionalIterable`: RSConnect API _raw_query return type issue
- [ ] `reportOptionalMemberAccess`: RSConnect API _raw_query return type issue, prepare_pin_version unhandled case
- [ ] `reportOptionalSubscript`: RSConnect API _raw_query return type issue, RSConnect implementation of the IFileSystem Protocol
- [ ] `reportPossiblyUnboundVariable`: Mostly False positives arising from fragmented if statements and integer comparisons
- [ ] `reportReturnType`: Variety of issues
```
